### ISSUE TITLE
Can we rename the repository from 'halt' to 'libLiFFT'?

### ISSUE THREAD

**Issue by bussmann** [ComputationalRadiationPhysics/liFFT#20]
Anybody against renaming the GitHub repo to libLiFFT? I want to reference to it but with the correct name.

**Comment by Flamefire** [comment]
Not from my site. What about @ax3l and @tdd11235813?

**Comment by tdd11235813** [comment]
libLiFFT or LiFFT?
[see comment by @ax3l](https://github.com/ComputationalRadiationPhysics/halt/issues/15#issuecomment-209122008)

**Comment by ax3l** [comment]
probably `liFFT` is easy and short.

don't forget to link against `libliFFT.so` ;)

**Comment by bussmann** [comment]
So it shall be!

**Comment by Flamefire** [comment]
Done. So we `liFFT` you up to no `halt`s
