### ISSUE TITLE
Use a more descriptive namspace than foobar

### ISSUE THREAD

**Issue by mxmlnkn** [ComputationalRadiationPhysics/liFFT#9]
Arguably 'foobar' is the least descriptive name. I strongly suggest using another one, e.g. `sed 's/foobar/HaLT/g'`

**Comment by bussmann** [comment]
'GEPUFFT' GEneral Platform-Unifying FFT

**Comment by mxmlnkn** [comment]
I'm sure we can find some acronym to match `PUmmeluFFT` :)
